# Site settings
title: Aryan Gomes - Web Developer
description: 
baseurl: '' # for test: remove string '/space-jekyll-templa' to ''
url: "http://aryangomes.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https:yourusername.githu.io'
# User settings
username: aryangomes
user_title: Aryan Gomes
email: aryan.gomes@gmail.com
twitter_username: _aryangomes
github_username:  aryangomes

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: about me
    url: /about
# projects in header index
projects:
  - name: ControladorFinanceiroApp
    url: 
  - name: Sistema de Gerência de Lanchonete(SGL)
    url: https://github.com/aryangomes/applanchonete
  - name: Sistema de Automação de Biblioteca "Librorum"
    url: 
  - name: Sistema de Gerência de Dizimistas
    url: 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
